name: santaroso
services:
  webserver:
    image: 8ct8pus/apache-php-fpm-alpine:2.5.2
    extra_hosts:
      - "host.docker.internal:host-gateway"
    hostname: testing
    ports:
      - "80:80"
      - "443:443"
      - "8025:8025"
    volumes:
      - ../website/:/sites/localhost/html/public/
      - ./docker/etc/:/docker/etc/
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'santaroso_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3306:3306"
    volumes:
      - ./data/conf.d:/etc/mysql/conf.d
      - ./data/logs:/logs
      - ../db:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db_data: